name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        # macOS is not included due to the exclusion in Travis CI config
        # compiler: [gcc, clang] # Uncomment and adjust if needed for specific compilers

    steps:
    - uses: actions/checkout@v2

    - name: Set up C environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Clone JWasm regressions
      run: git clone https://github.com/JWasm/JWasm-regressions.git Regress

    - name: Build
      run: make -s -f GccUnix.mak

    - name: Run tests
      run: |        
        export PATH=${{ github.workspace }}/GccUnixR:$PATH                
        cd Regress        
        ./test-linux.sh

#    - name: Extract tag name
#      id: extract_tag
#      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Package
      run: |
        tar -czvf jwasm-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz -C GccUnixR jwasm
    
    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release  ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jwasm-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz
        path: ./jwasm-${{ github.run_id }}-${{ github.sha }}-linux-x86_64.tar.gz
